#!/usr/bin/env bash
set -eou pipefail

cd "$(git rev-parse --show-toplevel)"

source scripts/env

./scripts/util/build tools

docker run "${COMMON_RUN_ARGS[@]}" \
           --tty \
           --mount "type=bind,src=${PWD},dst=${PWD}" \
           --workdir "${PWD}" \
           "${APP_NAME}-tools:latest" \
           "${@}"
