services:
  app:
    image: registry.poppet.io/ccc-app:latest
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres

  comfyui:
    image: registry.poppet.io/ccc-comfyui:latest
    ports:
      - 8188:8188
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    shm_size: '32g'
    restart: always
    volumes:
      - ./data/comfyui/models:/app/ComfyUI/models
    profiles:
      - dev


  postgres:
    image: registry.poppet.io/dockerhub/library/postgres:18.0-trixie
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example


volumes:
  db-data:
