services:
  app:
    image: registry.poppet.io/ccc-app:latest
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db

  postgres:
    image: registry.poppet.io/dockerhub/library/postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example


volumes:
  db-data:
